### ISSUE TITLE
Title hidden under top nav when jumping to a section

### ISSUE THREAD

**Issue by ctargett** [ctargett/refguide-asciidoc-poc#12]
Clicking on a section link (like in the TOC of a page), jumps you to the section, but the title of the section is hidden under the top nav bar. At least that's what I think is happening...it could be actually jumping you to _after_ the title.

I modified the original code from the theme we're using, I may have messed something up with the padding/margins that's making this happen. Compare with this: http://idratherbewriting.com/documentation-theme-jekyll/index.html, which is the theme we're using.

**Comment by hossman** [comment]
I actaully see the same issue on the http://idratherbewriting.com site that i do in ours.

I remember the main Solr site (which has a similar "floating header" had this same problem for a while, i think the fix was the top, padding-top, and margin-bottom settings in the `offset` css class here...

http://svn.apache.org/viewvc/lucene/cms/trunk/content/solr/assets/styles/base.css?view=markup#l38

**Comment by ctargett** [comment]
Oh strange. I had rather heavily edited one of the CSS that came with the theme, and when I put the original one back, the problem goes away...in Chrome.

Using Safari, however, I see the same problem with both sites. So, ugh. Browser-specific. How fun.

**Comment by ctargett** [comment]
Oh! It's related to width. If I make Safari window wider, it behaves properly.

**Comment by ctargett** [comment]
Closing - what I did a couple weeks ago seems to be working all right now.
