### ISSUE TITLE
<em> (and <strong>?) tags inside of <code> tags are getting lost in conversion

### ISSUE THREAD

**Issue by hossman** [ctargett/refguide-asciidoc-poc#14]
I need to dig into this more, but AFAICT pandoc is throwing away any formatting tags that exist inside of inline code tags (even though asciidoctor's docs say that should work fine), for example:

confluence-export/cleaned-export/collections-api.html

```
<code>/admin/collections?action=CREATE&amp;name=<em>name</em>&amp;numShards=<em>number</em>&amp;replicationFactor=<em>number</em>&amp;maxShardsPerNode=<em>number</em>&amp;createNodeSet=<em>nodelist</em>&amp;collection.configName=<em>configname</em></code>
```

**Comment by ctargett** [comment]
It might help to recall that Pandocs is converting to asciidoc format, and asciidoctor, what we are using, is a fork and refactor of asciidoc that has since been extended. Pandocs doesn't convert to asciidoctor. 

The changes between the two are documented here: http://asciidoctor.org/docs/user-manual/#migrating-from-asciidoc-python.

**Comment by hossman** [comment]
> Pandocs doesn't convert to asciidoctor. 
> Ah, yeah ... i keep forgetting ... in any case, I can "trick" pandoc by adding my own asciidoctor markup in the HTML markup which gets passed through as is ... fix soon, just spot checking a bunch of output to see if it's broken anywhere.
